version: '3.8'

services:
  jyl-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jyl-app
    ports:
      - "3000:3000"
    volumes:
      - ../storage:/app/storage
      - ./.env_docker:/app/server/.env
    depends_on:
      - jyl-db
    restart: always

  jyl-db:
    image: mysql:8.0
    container_name: jyl-db
    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-liang029209}
      MYSQL_DATABASE: ${DB_NAME:-jyl}
      MYSQL_USER: ${DB_USER:-jeje}
      MYSQL_PASSWORD: ${DB_PASS:-liang029209}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
