version: '3.8'

services:
  jyl-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jyl-app
    ports:
      - "9292:3000"
    volumes:
      - ../storage:/app/storage
    env_file:
      - .env_docker
    environment:
      - DB_HOST=jyl-db
    depends_on:
      jyl-db:
        condition: service_healthy
    restart: always

  jyl-db:
    image: mysql:8.0
    container_name: jyl-db
    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
    env_file:
      - .env_docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always

volumes:
  mysql_data:
