version: '3.8'

services:
  jyl-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jyl-app
    ports:
      - "9292:3000"
    volumes:
      - ../storage:/app/storage
      - ./.env_docker:/app/server/.env
    env_file:
      - .env_docker
    depends_on:
      - jyl-db
    restart: always

  jyl-db:
    image: mysql:8.0
    container_name: jyl-db
    command: --default-authentication-plugin=mysql_native_password --skip-host-cache --skip-name-resolve
    env_file:
      - .env_docker
    environment:
      MYSQL_ROOT_PASSWORD: jeje_123456
      MYSQL_DATABASE: jyl
      MYSQL_USER: jeje
      MYSQL_PASSWORD: jeje_123456
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
